//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 10:06:02 AM CST 
//


package main.java.com.cts.ptms.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.theopentutorials.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ConfirmResponseObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.theopentutorials.jaxb.beans
     * 
     */
    public ConfirmResponseObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse }
     * 
     */
    public ShipmentConfirmResponse createShipmentConfirmResponse() {
        return new ShipmentConfirmResponse();
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse.BillingWeight }
     * 
     */
    public ShipmentConfirmResponse.BillingWeight createShipmentConfirmResponseBillingWeight() {
        return new ShipmentConfirmResponse.BillingWeight();
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse.ShipmentCharges }
     * 
     */
    public ShipmentConfirmResponse.ShipmentCharges createShipmentConfirmResponseShipmentCharges() {
        return new ShipmentConfirmResponse.ShipmentCharges();
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse.Response }
     * 
     */
    public ShipmentConfirmResponse.Response createShipmentConfirmResponseResponse() {
        return new ShipmentConfirmResponse.Response();
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse.BillingWeight.UnitOfMeasurement }
     * 
     */
    public ShipmentConfirmResponse.BillingWeight.UnitOfMeasurement createShipmentConfirmResponseBillingWeightUnitOfMeasurement() {
        return new ShipmentConfirmResponse.BillingWeight.UnitOfMeasurement();
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse.ShipmentCharges.TransportationCharges }
     * 
     */
    public ShipmentConfirmResponse.ShipmentCharges.TransportationCharges createShipmentConfirmResponseShipmentChargesTransportationCharges() {
        return new ShipmentConfirmResponse.ShipmentCharges.TransportationCharges();
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse.ShipmentCharges.ServiceOptionsCharges }
     * 
     */
    public ShipmentConfirmResponse.ShipmentCharges.ServiceOptionsCharges createShipmentConfirmResponseShipmentChargesServiceOptionsCharges() {
        return new ShipmentConfirmResponse.ShipmentCharges.ServiceOptionsCharges();
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse.ShipmentCharges.TotalCharges }
     * 
     */
    public ShipmentConfirmResponse.ShipmentCharges.TotalCharges createShipmentConfirmResponseShipmentChargesTotalCharges() {
        return new ShipmentConfirmResponse.ShipmentCharges.TotalCharges();
    }

    /**
     * Create an instance of {@link ShipmentConfirmResponse.Response.TransactionReference }
     * 
     */
    public ShipmentConfirmResponse.Response.TransactionReference createShipmentConfirmResponseResponseTransactionReference() {
        return new ShipmentConfirmResponse.Response.TransactionReference();
    }

}
