//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 03:39:27 PM CST 
//


package main.java.com.cts.ptms.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}SHIP_UNIT"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}LabelOutputFileType"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}ReportOutputFileType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MSN" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shipunit",
    "labelOutputFileType",
    "reportOutputFileType"
})
@XmlRootElement(name = "CREATE_SHIP_UNITS_PARAMS1")
public class CREATESHIPUNITSPARAMS1 {

    @XmlElement(name = "SHIP_UNIT", required = true)
    protected SHIPUNIT shipunit;
    @XmlElement(name = "LabelOutputFileType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String labelOutputFileType;
    @XmlElement(name = "ReportOutputFileType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String reportOutputFileType;
    @XmlAttribute(name = "MSN", required = true)
    protected BigInteger msn;

    /**
     * Gets the value of the shipunit property.
     * 
     * @return
     *     possible object is
     *     {@link SHIPUNIT }
     *     
     */
    public SHIPUNIT getSHIPUNIT() {
        return shipunit;
    }

    /**
     * Sets the value of the shipunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link SHIPUNIT }
     *     
     */
    public void setSHIPUNIT(SHIPUNIT value) {
        this.shipunit = value;
    }

    /**
     * Gets the value of the labelOutputFileType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelOutputFileType() {
        return labelOutputFileType;
    }

    /**
     * Sets the value of the labelOutputFileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelOutputFileType(String value) {
        this.labelOutputFileType = value;
    }

    /**
     * Gets the value of the reportOutputFileType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportOutputFileType() {
        return reportOutputFileType;
    }

    /**
     * Sets the value of the reportOutputFileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportOutputFileType(String value) {
        this.reportOutputFileType = value;
    }

    /**
     * Gets the value of the msn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMSN() {
        return msn;
    }

    /**
     * Sets the value of the msn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMSN(BigInteger value) {
        this.msn = value;
    }

}
