//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 03:39:27 PM CST 
//


package main.java.com.cts.ptms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}CREATE_SHIP_UNITS_PARAMS1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createshipunitsparams1"
})
@XmlRootElement(name = "CreateShipUnitsParams", namespace = "")
public class CreateShipUnitsParams {

    @XmlElement(name = "CREATE_SHIP_UNITS_PARAMS1", required = true)
    protected CREATESHIPUNITSPARAMS1 createshipunitsparams1;

    /**
     * Gets the value of the createshipunitsparams1 property.
     * 
     * @return
     *     possible object is
     *     {@link CREATESHIPUNITSPARAMS1 }
     *     
     */
    public CREATESHIPUNITSPARAMS1 getCREATESHIPUNITSPARAMS1() {
        return createshipunitsparams1;
    }

    /**
     * Sets the value of the createshipunitsparams1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CREATESHIPUNITSPARAMS1 }
     *     
     */
    public void setCREATESHIPUNITSPARAMS1(CREATESHIPUNITSPARAMS1 value) {
        this.createshipunitsparams1 = value;
    }

}
