//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 03:39:27 PM CST 
//


package main.java.com.cts.ptms.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cts.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class GLSObjectFactory {

    private final static QName _CarrierReferenceType_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "CarrierReferenceType");
    private final static QName _CartonName_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "CartonName");
    private final static QName _CarrierReferenceNote_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "CarrierReferenceNote");
    private final static QName _IndividualName_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "IndividualName");
    private final static QName _ShipmentTotal_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "ShipmentTotal");
    private final static QName _CustomerReferenceType2_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "CustomerReferenceType2");
    private final static QName _Quantity_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "Quantity");
    private final static QName _Width_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "Width");
    private final static QName _LabelOutputFileType_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "LabelOutputFileType");
    private final static QName _Height_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "Height");
    private final static QName _BillingAccountID_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "BillingAccountID");
    private final static QName _CustomerOrderNumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "CustomerOrderNumber");
    private final static QName _UnitPrice_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "UnitPrice");
    private final static QName _ZIPCode_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "ZIPCode");
    private final static QName _TotalPrice_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "TotalPrice");
    private final static QName _TCNumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "TCNumber");
    private final static QName _ShipVia_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "ShipVia");
    private final static QName _ReportOutputFileType_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "ReportOutputFileType");
    private final static QName _OrderNumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "OrderNumber");
    private final static QName _ShippingAndHandling_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "ShippingAndHandling");
    private final static QName _State_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "State");
    private final static QName _Length_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "Length");
    private final static QName _WaveNumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "WaveNumber");
    private final static QName _Description_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "Description");
    private final static QName _DistributionCenter_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "DistributionCenter");
    private final static QName _OrderKey_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "OrderKey");
    private final static QName _AddressID_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "AddressID");
    private final static QName _SubTotal_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "SubTotal");
    private final static QName _Class_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "Class");
    private final static QName _LineNumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "LineNumber");
    private final static QName _PhoneNumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "PhoneNumber");
    private final static QName _CustomerPONumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "CustomerPONumber");
    private final static QName _SalesTax_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "SalesTax");
    private final static QName _ItemNumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "ItemNumber");
    private final static QName _CartonNumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "CartonNumber");
    private final static QName _SecondaryDescription_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", "SecondaryDescription");
    private final static QName _CustomerReference2_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "CustomerReference2");
    private final static QName _Status_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "Status");
    private final static QName _Weight_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "Weight");
    private final static QName _PackagePONumber_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "PackagePONumber");
    private final static QName _Address1_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "Address1");
    private final static QName _City_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "City");
    private final static QName _SessionID_QNAME = new QName("", "SessionID");
    private final static QName _DatePlannedShipment_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "DatePlannedShipment");
    private final static QName _Address2_QNAME = new QName("http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", "Address2");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cts.test
     * 
     */
    public GLSObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateShipUnits }
     * 
     */
    public CreateShipUnits createCreateShipUnits() {
        return new CreateShipUnits();
    }

    /**
     * Create an instance of {@link CreateShipUnitsParams }
     * 
     */
    public CreateShipUnitsParams createCreateShipUnitsParams() {
        return new CreateShipUnitsParams();
    }

    /**
     * Create an instance of {@link CREATESHIPUNITSPARAMS1 }
     * 
     */
    public CREATESHIPUNITSPARAMS1 createCREATESHIPUNITSPARAMS1() {
        return new CREATESHIPUNITSPARAMS1();
    }

    /**
     * Create an instance of {@link SHIPUNIT }
     * 
     */
    public SHIPUNIT createSHIPUNIT() {
        return new SHIPUNIT();
    }

    /**
     * Create an instance of {@link ShippingOptions }
     * 
     */
    public ShippingOptions createShippingOptions() {
        return new ShippingOptions();
    }

    /**
     * Create an instance of {@link DataXML }
     * 
     */
    public DataXML createDataXML() {
        return new DataXML();
    }

    /**
     * Create an instance of {@link SHIPUNITCUSTOM }
     * 
     */
    public SHIPUNITCUSTOM createSHIPUNITCUSTOM() {
        return new SHIPUNITCUSTOM();
    }

    /**
     * Create an instance of {@link INVOICE }
     * 
     */
    public INVOICE createINVOICE() {
        return new INVOICE();
    }

    /**
     * Create an instance of {@link ITEM }
     * 
     */
    public ITEM createITEM() {
        return new ITEM();
    }

    /**
     * Create an instance of {@link ADDRESS }
     * 
     */
    public ADDRESS createADDRESS() {
        return new ADDRESS();
    }

    /**
     * Create an instance of {@link Address3 }
     * 
     */
    public Address3 createAddress3() {
        return new Address3();
    }

    /**
     * Create an instance of {@link Address4 }
     * 
     */
    public Address4 createAddress4() {
        return new Address4();
    }

    /**
     * Create an instance of {@link INTERNATIONALSHIPUNIT }
     * 
     */
    public INTERNATIONALSHIPUNIT createINTERNATIONALSHIPUNIT() {
        return new INTERNATIONALSHIPUNIT();
    }

    /**
     * Create an instance of {@link UPSSHIPUNIT }
     * 
     */
    public UPSSHIPUNIT createUPSSHIPUNIT() {
        return new UPSSHIPUNIT();
    }

    /**
     * Create an instance of {@link FEDEXSHIPUNIT }
     * 
     */
    public FEDEXSHIPUNIT createFEDEXSHIPUNIT() {
        return new FEDEXSHIPUNIT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "CarrierReferenceType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCarrierReferenceType(String value) {
        return new JAXBElement<String>(_CarrierReferenceType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "CartonName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCartonName(String value) {
        return new JAXBElement<String>(_CartonName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "CarrierReferenceNote")
    public JAXBElement<BigInteger> createCarrierReferenceNote(BigInteger value) {
        return new JAXBElement<BigInteger>(_CarrierReferenceNote_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "IndividualName")
    public JAXBElement<String> createIndividualName(String value) {
        return new JAXBElement<String>(_IndividualName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "ShipmentTotal")
    public JAXBElement<BigDecimal> createShipmentTotal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ShipmentTotal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "CustomerReferenceType2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCustomerReferenceType2(String value) {
        return new JAXBElement<String>(_CustomerReferenceType2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "Quantity")
    public JAXBElement<BigInteger> createQuantity(BigInteger value) {
        return new JAXBElement<BigInteger>(_Quantity_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "Width")
    public JAXBElement<BigInteger> createWidth(BigInteger value) {
        return new JAXBElement<BigInteger>(_Width_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "LabelOutputFileType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLabelOutputFileType(String value) {
        return new JAXBElement<String>(_LabelOutputFileType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "Height")
    public JAXBElement<BigInteger> createHeight(BigInteger value) {
        return new JAXBElement<BigInteger>(_Height_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "BillingAccountID")
    public JAXBElement<BigInteger> createBillingAccountID(BigInteger value) {
        return new JAXBElement<BigInteger>(_BillingAccountID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "CustomerOrderNumber")
    public JAXBElement<BigInteger> createCustomerOrderNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerOrderNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "UnitPrice")
    public JAXBElement<BigDecimal> createUnitPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_UnitPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "ZIPCode")
    public JAXBElement<BigInteger> createZIPCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_ZIPCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "TotalPrice")
    public JAXBElement<BigDecimal> createTotalPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TotalPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "TCNumber")
    public JAXBElement<BigInteger> createTCNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_TCNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "ShipVia")
    public JAXBElement<BigInteger> createShipVia(BigInteger value) {
        return new JAXBElement<BigInteger>(_ShipVia_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "ReportOutputFileType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReportOutputFileType(String value) {
        return new JAXBElement<String>(_ReportOutputFileType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "OrderNumber")
    public JAXBElement<BigInteger> createOrderNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_OrderNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "ShippingAndHandling")
    public JAXBElement<BigDecimal> createShippingAndHandling(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ShippingAndHandling_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "State")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "Length")
    public JAXBElement<BigInteger> createLength(BigInteger value) {
        return new JAXBElement<BigInteger>(_Length_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "WaveNumber")
    public JAXBElement<BigInteger> createWaveNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_WaveNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "DistributionCenter")
    public JAXBElement<BigInteger> createDistributionCenter(BigInteger value) {
        return new JAXBElement<BigInteger>(_DistributionCenter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "OrderKey")
    public JAXBElement<BigInteger> createOrderKey(BigInteger value) {
        return new JAXBElement<BigInteger>(_OrderKey_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "AddressID")
    public JAXBElement<BigInteger> createAddressID(BigInteger value) {
        return new JAXBElement<BigInteger>(_AddressID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "SubTotal")
    public JAXBElement<BigDecimal> createSubTotal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SubTotal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "Class")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createClass(String value) {
        return new JAXBElement<String>(_Class_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "LineNumber")
    public JAXBElement<BigInteger> createLineNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_LineNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "PhoneNumber")
    public JAXBElement<BigInteger> createPhoneNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_PhoneNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "CustomerPONumber")
    public JAXBElement<BigInteger> createCustomerPONumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerPONumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "SalesTax")
    public JAXBElement<BigDecimal> createSalesTax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SalesTax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "ItemNumber")
    public JAXBElement<BigInteger> createItemNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_ItemNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "CartonNumber")
    public JAXBElement<BigInteger> createCartonNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_CartonNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/Walmart_1.00.0000.xsd", name = "SecondaryDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSecondaryDescription(String value) {
        return new JAXBElement<String>(_SecondaryDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "CustomerReference2")
    public JAXBElement<BigInteger> createCustomerReference2(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerReference2_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "Status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "Weight")
    public JAXBElement<BigInteger> createWeight(BigInteger value) {
        return new JAXBElement<BigInteger>(_Weight_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "PackagePONumber")
    public JAXBElement<BigInteger> createPackagePONumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_PackagePONumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "Address1")
    public JAXBElement<String> createAddress1(String value) {
        return new JAXBElement<String>(_Address1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "City")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SessionID")
    public JAXBElement<BigInteger> createSessionID(BigInteger value) {
        return new JAXBElement<BigInteger>(_SessionID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "DatePlannedShipment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDatePlannedShipment(String value) {
        return new JAXBElement<String>(_DatePlannedShipment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", name = "Address2")
    public JAXBElement<String> createAddress2(String value) {
        return new JAXBElement<String>(_Address2_QNAME, String.class, null, value);
    }

}
