//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 03:39:27 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.com.cts.ptms.model;
