//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 11:50:56 AM CST 
//


package main.java.com.cts.ptms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TransactionReference">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RequestAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RequestOption" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipmentDigest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "shipmentDigest"
})
@XmlRootElement(name = "ShipmentAcceptRequest")
public class ShipmentAcceptRequest {

    @XmlElement(name = "Request", required = true)
    protected ShipmentAcceptRequest.Request request;
    @XmlElement(name = "ShipmentDigest", required = true)
    protected String shipmentDigest;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentAcceptRequest.Request }
     *     
     */
    public ShipmentAcceptRequest.Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentAcceptRequest.Request }
     *     
     */
    public void setRequest(ShipmentAcceptRequest.Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the shipmentDigest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentDigest() {
        return shipmentDigest;
    }

    /**
     * Sets the value of the shipmentDigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentDigest(String value) {
        this.shipmentDigest = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TransactionReference">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RequestAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RequestOption" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionReference",
        "requestAction",
        "requestOption"
    })
    public static class Request {

        @XmlElement(name = "TransactionReference", required = true)
        protected ShipmentAcceptRequest.Request.TransactionReference transactionReference;
        @XmlElement(name = "RequestAction", required = true)
        protected String requestAction;
        @XmlElement(name = "RequestOption")
        protected String requestOption;

        /**
         * Gets the value of the transactionReference property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentAcceptRequest.Request.TransactionReference }
         *     
         */
        public ShipmentAcceptRequest.Request.TransactionReference getTransactionReference() {
            return transactionReference;
        }

        /**
         * Sets the value of the transactionReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentAcceptRequest.Request.TransactionReference }
         *     
         */
        public void setTransactionReference(ShipmentAcceptRequest.Request.TransactionReference value) {
            this.transactionReference = value;
        }

        /**
         * Gets the value of the requestAction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestAction() {
            return requestAction;
        }

        /**
         * Sets the value of the requestAction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestAction(String value) {
            this.requestAction = value;
        }

        /**
         * Gets the value of the requestOption property.
         * 
         */
        public String getRequestOption() {
            return requestOption;
        }

        /**
         * Sets the value of the requestOption property.
         * 
         */
        public void setRequestOption(String value) {
            this.requestOption = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customerContext"
        })
        public static class TransactionReference {

            @XmlElement(name = "CustomerContext", required = true)
            protected String customerContext;

            /**
             * Gets the value of the customerContext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerContext() {
                return customerContext;
            }

            /**
             * Sets the value of the customerContext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerContext(String value) {
                this.customerContext = value;
            }

        }

    }

}
