//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 11:52:29 AM CST 
//


package main.java.com.cts.ptms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Response">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TransactionReference">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ResponseStatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ResponseStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipmentResults">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ShipmentCharges">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TransportationCharges">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ServiceOptionsCharges">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="TotalCharges">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="BillingWeight">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="UnitOfMeasurement">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ShipmentIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PackageResults">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ServiceOptionsCharges">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="LabelImage">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="LabelImageFormat">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="GraphicImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="HTMLImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "shipmentResults"
})
@XmlRootElement(name = "ShipmentAcceptResponse")
public class ShipmentAcceptResponse {

    @XmlElement(name = "Response", required = true)
    protected ShipmentAcceptResponse.Response response;
    @XmlElement(name = "ShipmentResults", required = true)
    protected ShipmentAcceptResponse.ShipmentResults shipmentResults;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentAcceptResponse.Response }
     *     
     */
    public ShipmentAcceptResponse.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentAcceptResponse.Response }
     *     
     */
    public void setResponse(ShipmentAcceptResponse.Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the shipmentResults property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentAcceptResponse.ShipmentResults }
     *     
     */
    public ShipmentAcceptResponse.ShipmentResults getShipmentResults() {
        return shipmentResults;
    }

    /**
     * Sets the value of the shipmentResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentAcceptResponse.ShipmentResults }
     *     
     */
    public void setShipmentResults(ShipmentAcceptResponse.ShipmentResults value) {
        this.shipmentResults = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TransactionReference">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ResponseStatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ResponseStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionReference",
        "responseStatusCode",
        "responseStatusDescription",
        "error"
    })
    public static class Response {

        @XmlElement(name = "TransactionReference", required = true)
        protected ShipmentAcceptResponse.Response.TransactionReference transactionReference;
        @XmlElement(name = "ResponseStatusCode")
        protected byte responseStatusCode;
        @XmlElement(name = "ResponseStatusDescription", required = true)
        protected String responseStatusDescription;
        @XmlElement(name = "Error")
        public Error error = new Error();
        /**
         * Gets the value of the transactionReference property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentAcceptResponse.Response.TransactionReference }
         *     
         */
        public ShipmentAcceptResponse.Response.TransactionReference getTransactionReference() {
            return transactionReference;
        }

        /**
         * Sets the value of the transactionReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentAcceptResponse.Response.TransactionReference }
         *     
         */
        public void setTransactionReference(ShipmentAcceptResponse.Response.TransactionReference value) {
            this.transactionReference = value;
        }

        /**
         * Gets the value of the responseStatusCode property.
         * 
         */
        public byte getResponseStatusCode() {
            return responseStatusCode;
        }

        /**
         * Sets the value of the responseStatusCode property.
         * 
         */
        public void setResponseStatusCode(byte value) {
            this.responseStatusCode = value;
        }

        /**
         * Gets the value of the responseStatusDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseStatusDescription() {
            return responseStatusDescription;
        }

        /**
         * Sets the value of the responseStatusDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseStatusDescription(String value) {
            this.responseStatusDescription = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customerContext"
        })
        public static class TransactionReference {

            @XmlElement(name = "CustomerContext", required = true)
            protected String customerContext;

            /**
             * Gets the value of the customerContext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerContext() {
                return customerContext;
            }

            /**
             * Sets the value of the customerContext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerContext(String value) {
                this.customerContext = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ShipmentCharges">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TransportationCharges">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ServiceOptionsCharges">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="TotalCharges">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BillingWeight">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="UnitOfMeasurement">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ShipmentIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PackageResults">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ServiceOptionsCharges">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="LabelImage">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="LabelImageFormat">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="GraphicImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="HTMLImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shipmentCharges",
        "billingWeight",
        "shipmentIdentificationNumber",
        "packageResults"
    })
    public static class ShipmentResults {

        @XmlElement(name = "ShipmentCharges", required = true)
        protected ShipmentAcceptResponse.ShipmentResults.ShipmentCharges shipmentCharges;
        @XmlElement(name = "BillingWeight", required = true)
        protected ShipmentAcceptResponse.ShipmentResults.BillingWeight billingWeight;
        @XmlElement(name = "ShipmentIdentificationNumber", required = true)
        protected String shipmentIdentificationNumber;
        @XmlElement(name = "PackageResults", required = true)
        protected ShipmentAcceptResponse.ShipmentResults.PackageResults packageResults;

        /**
         * Gets the value of the shipmentCharges property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges }
         *     
         */
        public ShipmentAcceptResponse.ShipmentResults.ShipmentCharges getShipmentCharges() {
            return shipmentCharges;
        }

        /**
         * Sets the value of the shipmentCharges property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges }
         *     
         */
        public void setShipmentCharges(ShipmentAcceptResponse.ShipmentResults.ShipmentCharges value) {
            this.shipmentCharges = value;
        }

        /**
         * Gets the value of the billingWeight property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentAcceptResponse.ShipmentResults.BillingWeight }
         *     
         */
        public ShipmentAcceptResponse.ShipmentResults.BillingWeight getBillingWeight() {
            return billingWeight;
        }

        /**
         * Sets the value of the billingWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentAcceptResponse.ShipmentResults.BillingWeight }
         *     
         */
        public void setBillingWeight(ShipmentAcceptResponse.ShipmentResults.BillingWeight value) {
            this.billingWeight = value;
        }

        /**
         * Gets the value of the shipmentIdentificationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipmentIdentificationNumber() {
            return shipmentIdentificationNumber;
        }

        /**
         * Sets the value of the shipmentIdentificationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipmentIdentificationNumber(String value) {
            this.shipmentIdentificationNumber = value;
        }

        /**
         * Gets the value of the packageResults property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentAcceptResponse.ShipmentResults.PackageResults }
         *     
         */
        public ShipmentAcceptResponse.ShipmentResults.PackageResults getPackageResults() {
            return packageResults;
        }

        /**
         * Sets the value of the packageResults property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentAcceptResponse.ShipmentResults.PackageResults }
         *     
         */
        public void setPackageResults(ShipmentAcceptResponse.ShipmentResults.PackageResults value) {
            this.packageResults = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="UnitOfMeasurement">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "unitOfMeasurement",
            "weight"
        })
        public static class BillingWeight {

            @XmlElement(name = "UnitOfMeasurement", required = true)
            protected ShipmentAcceptResponse.ShipmentResults.BillingWeight.UnitOfMeasurement unitOfMeasurement;
            @XmlElement(name = "Weight")
            protected float weight;

            /**
             * Gets the value of the unitOfMeasurement property.
             * 
             * @return
             *     possible object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.BillingWeight.UnitOfMeasurement }
             *     
             */
            public ShipmentAcceptResponse.ShipmentResults.BillingWeight.UnitOfMeasurement getUnitOfMeasurement() {
                return unitOfMeasurement;
            }

            /**
             * Sets the value of the unitOfMeasurement property.
             * 
             * @param value
             *     allowed object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.BillingWeight.UnitOfMeasurement }
             *     
             */
            public void setUnitOfMeasurement(ShipmentAcceptResponse.ShipmentResults.BillingWeight.UnitOfMeasurement value) {
                this.unitOfMeasurement = value;
            }

            /**
             * Gets the value of the weight property.
             * 
             */
            public float getWeight() {
                return weight;
            }

            /**
             * Sets the value of the weight property.
             * 
             */
            public void setWeight(float value) {
                this.weight = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "code",
                "description"
            })
            public static class UnitOfMeasurement {

                @XmlElement(name = "Code", required = true)
                protected String code;
                @XmlElement(name = "Description", required = true)
                protected String description;

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ServiceOptionsCharges">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="LabelImage">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="LabelImageFormat">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="GraphicImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="HTMLImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trackingNumber",
            "serviceOptionsCharges",
            "labelImage"
        })
        public static class PackageResults {

            @XmlElement(name = "TrackingNumber", required = true)
            protected String trackingNumber;
            @XmlElement(name = "ServiceOptionsCharges", required = true)
            protected ShipmentAcceptResponse.ShipmentResults.PackageResults.ServiceOptionsCharges serviceOptionsCharges;
            @XmlElement(name = "LabelImage", required = true)
            protected ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage labelImage;

            /**
             * Gets the value of the trackingNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTrackingNumber() {
                return trackingNumber;
            }

            /**
             * Sets the value of the trackingNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTrackingNumber(String value) {
                this.trackingNumber = value;
            }

            /**
             * Gets the value of the serviceOptionsCharges property.
             * 
             * @return
             *     possible object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.ServiceOptionsCharges }
             *     
             */
            public ShipmentAcceptResponse.ShipmentResults.PackageResults.ServiceOptionsCharges getServiceOptionsCharges() {
                return serviceOptionsCharges;
            }

            /**
             * Sets the value of the serviceOptionsCharges property.
             * 
             * @param value
             *     allowed object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.ServiceOptionsCharges }
             *     
             */
            public void setServiceOptionsCharges(ShipmentAcceptResponse.ShipmentResults.PackageResults.ServiceOptionsCharges value) {
                this.serviceOptionsCharges = value;
            }

            /**
             * Gets the value of the labelImage property.
             * 
             * @return
             *     possible object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage }
             *     
             */
            public ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage getLabelImage() {
                return labelImage;
            }

            /**
             * Sets the value of the labelImage property.
             * 
             * @param value
             *     allowed object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage }
             *     
             */
            public void setLabelImage(ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage value) {
                this.labelImage = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="LabelImageFormat">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="GraphicImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="HTMLImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "labelImageFormat",
                "graphicImage",
                "htmlImage"
            })
            public static class LabelImage {

                @XmlElement(name = "LabelImageFormat", required = true)
                protected ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage.LabelImageFormat labelImageFormat;
                @XmlElement(name = "GraphicImage", required = true)
                protected String graphicImage;
                @XmlElement(name = "HTMLImage", required = true)
                protected String htmlImage;

                /**
                 * Gets the value of the labelImageFormat property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage.LabelImageFormat }
                 *     
                 */
                public ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage.LabelImageFormat getLabelImageFormat() {
                    return labelImageFormat;
                }

                /**
                 * Sets the value of the labelImageFormat property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage.LabelImageFormat }
                 *     
                 */
                public void setLabelImageFormat(ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage.LabelImageFormat value) {
                    this.labelImageFormat = value;
                }

                /**
                 * Gets the value of the graphicImage property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGraphicImage() {
                    return graphicImage;
                }

                /**
                 * Sets the value of the graphicImage property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGraphicImage(String value) {
                    this.graphicImage = value;
                }

                /**
                 * Gets the value of the htmlImage property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHTMLImage() {
                    return htmlImage;
                }

                /**
                 * Sets the value of the htmlImage property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHTMLImage(String value) {
                    this.htmlImage = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "code"
                })
                public static class LabelImageFormat {

                    @XmlElement(name = "Code", required = true)
                    protected String code;

                    /**
                     * Gets the value of the code property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCode() {
                        return code;
                    }

                    /**
                     * Sets the value of the code property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCode(String value) {
                        this.code = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "currencyCode",
                "monetaryValue"
            })
            public static class ServiceOptionsCharges {

                @XmlElement(name = "CurrencyCode", required = true)
                protected String currencyCode;
                @XmlElement(name = "MonetaryValue")
                protected float monetaryValue;

                /**
                 * Gets the value of the currencyCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurrencyCode() {
                    return currencyCode;
                }

                /**
                 * Sets the value of the currencyCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurrencyCode(String value) {
                    this.currencyCode = value;
                }

                /**
                 * Gets the value of the monetaryValue property.
                 * 
                 */
                public float getMonetaryValue() {
                    return monetaryValue;
                }

                /**
                 * Sets the value of the monetaryValue property.
                 * 
                 */
                public void setMonetaryValue(float value) {
                    this.monetaryValue = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TransportationCharges">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ServiceOptionsCharges">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="TotalCharges">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "transportationCharges",
            "serviceOptionsCharges",
            "totalCharges"
        })
        public static class ShipmentCharges {

            @XmlElement(name = "TransportationCharges", required = true)
            protected ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TransportationCharges transportationCharges;
            @XmlElement(name = "ServiceOptionsCharges", required = true)
            protected ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.ServiceOptionsCharges serviceOptionsCharges;
            @XmlElement(name = "TotalCharges", required = true)
            protected ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TotalCharges totalCharges;

            /**
             * Gets the value of the transportationCharges property.
             * 
             * @return
             *     possible object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TransportationCharges }
             *     
             */
            public ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TransportationCharges getTransportationCharges() {
                return transportationCharges;
            }

            /**
             * Sets the value of the transportationCharges property.
             * 
             * @param value
             *     allowed object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TransportationCharges }
             *     
             */
            public void setTransportationCharges(ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TransportationCharges value) {
                this.transportationCharges = value;
            }

            /**
             * Gets the value of the serviceOptionsCharges property.
             * 
             * @return
             *     possible object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.ServiceOptionsCharges }
             *     
             */
            public ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.ServiceOptionsCharges getServiceOptionsCharges() {
                return serviceOptionsCharges;
            }

            /**
             * Sets the value of the serviceOptionsCharges property.
             * 
             * @param value
             *     allowed object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.ServiceOptionsCharges }
             *     
             */
            public void setServiceOptionsCharges(ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.ServiceOptionsCharges value) {
                this.serviceOptionsCharges = value;
            }

            /**
             * Gets the value of the totalCharges property.
             * 
             * @return
             *     possible object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TotalCharges }
             *     
             */
            public ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TotalCharges getTotalCharges() {
                return totalCharges;
            }

            /**
             * Sets the value of the totalCharges property.
             * 
             * @param value
             *     allowed object is
             *     {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TotalCharges }
             *     
             */
            public void setTotalCharges(ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TotalCharges value) {
                this.totalCharges = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "currencyCode",
                "monetaryValue"
            })
            public static class ServiceOptionsCharges {

                @XmlElement(name = "CurrencyCode", required = true)
                protected String currencyCode;
                @XmlElement(name = "MonetaryValue")
                protected float monetaryValue;

                /**
                 * Gets the value of the currencyCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurrencyCode() {
                    return currencyCode;
                }

                /**
                 * Sets the value of the currencyCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurrencyCode(String value) {
                    this.currencyCode = value;
                }

                /**
                 * Gets the value of the monetaryValue property.
                 * 
                 */
                public float getMonetaryValue() {
                    return monetaryValue;
                }

                /**
                 * Sets the value of the monetaryValue property.
                 * 
                 */
                public void setMonetaryValue(float value) {
                    this.monetaryValue = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "currencyCode",
                "monetaryValue"
            })
            public static class TotalCharges {

                @XmlElement(name = "CurrencyCode", required = true)
                protected String currencyCode;
                @XmlElement(name = "MonetaryValue")
                protected float monetaryValue;

                /**
                 * Gets the value of the currencyCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurrencyCode() {
                    return currencyCode;
                }

                /**
                 * Sets the value of the currencyCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurrencyCode(String value) {
                    this.currencyCode = value;
                }

                /**
                 * Gets the value of the monetaryValue property.
                 * 
                 */
                public float getMonetaryValue() {
                    return monetaryValue;
                }

                /**
                 * Sets the value of the monetaryValue property.
                 * 
                 */
                public void setMonetaryValue(float value) {
                    this.monetaryValue = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "currencyCode",
                "monetaryValue"
            })
            public static class TransportationCharges {

                @XmlElement(name = "CurrencyCode", required = true)
                protected String currencyCode;
                @XmlElement(name = "MonetaryValue")
                protected float monetaryValue;

                /**
                 * Gets the value of the currencyCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurrencyCode() {
                    return currencyCode;
                }

                /**
                 * Sets the value of the currencyCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurrencyCode(String value) {
                    this.currencyCode = value;
                }

                /**
                 * Gets the value of the monetaryValue property.
                 * 
                 */
                public float getMonetaryValue() {
                    return monetaryValue;
                }

                /**
                 * Sets the value of the monetaryValue property.
                 * 
                 */
                public void setMonetaryValue(float value) {
                    this.monetaryValue = value;
                }

            }

        }

    }

}
