//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 03:21:10 PM CST 
//


package main.java.com.cts.ptms.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.theopentutorials.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ShipmentObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.theopentutorials.jaxb.beans
     * 
     */
    public ShipmentObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest }
     * 
     */
    public ShipmentConfirmRequest createShipmentConfirmRequest() {
        return new ShipmentConfirmRequest();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment }
     * 
     */
    public ShipmentConfirmRequest.Shipment createShipmentConfirmRequestShipment() {
        return new ShipmentConfirmRequest.Shipment();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.Package }
     * 
     */
    public ShipmentConfirmRequest.Shipment.Package createShipmentConfirmRequestShipmentPackage() {
        return new ShipmentConfirmRequest.Shipment.Package();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.PaymentInformation }
     * 
     */
    public ShipmentConfirmRequest.Shipment.PaymentInformation createShipmentConfirmRequestShipmentPaymentInformation() {
        return new ShipmentConfirmRequest.Shipment.PaymentInformation();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.PaymentInformation.Prepaid }
     * 
     */
    public ShipmentConfirmRequest.Shipment.PaymentInformation.Prepaid createShipmentConfirmRequestShipmentPaymentInformationPrepaid() {
        return new ShipmentConfirmRequest.Shipment.PaymentInformation.Prepaid();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.ShipFrom }
     * 
     */
    public ShipmentConfirmRequest.Shipment.ShipFrom createShipmentConfirmRequestShipmentShipFrom() {
        return new ShipmentConfirmRequest.Shipment.ShipFrom();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.ShipTo }
     * 
     */
    public ShipmentConfirmRequest.Shipment.ShipTo createShipmentConfirmRequestShipmentShipTo() {
        return new ShipmentConfirmRequest.Shipment.ShipTo();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.Shipper }
     * 
     */
    public ShipmentConfirmRequest.Shipment.Shipper createShipmentConfirmRequestShipmentShipper() {
        return new ShipmentConfirmRequest.Shipment.Shipper();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.LabelSpecification }
     * 
     */
    public ShipmentConfirmRequest.LabelSpecification createShipmentConfirmRequestLabelSpecification() {
        return new ShipmentConfirmRequest.LabelSpecification();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Request }
     * 
     */
    public ShipmentConfirmRequest.Request createShipmentConfirmRequestRequest() {
        return new ShipmentConfirmRequest.Request();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.RateInformation }
     * 
     */
    public ShipmentConfirmRequest.Shipment.RateInformation createShipmentConfirmRequestShipmentRateInformation() {
        return new ShipmentConfirmRequest.Shipment.RateInformation();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.Service }
     * 
     */
    public ShipmentConfirmRequest.Shipment.Service createShipmentConfirmRequestShipmentService() {
        return new ShipmentConfirmRequest.Shipment.Service();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.Package.PackagingType }
     * 
     */
    public ShipmentConfirmRequest.Shipment.Package.PackagingType createShipmentConfirmRequestShipmentPackagePackagingType() {
        return new ShipmentConfirmRequest.Shipment.Package.PackagingType();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.Package.ReferenceNumber }
     * 
     */
    public ShipmentConfirmRequest.Shipment.Package.ReferenceNumber createShipmentConfirmRequestShipmentPackageReferenceNumber() {
        return new ShipmentConfirmRequest.Shipment.Package.ReferenceNumber();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.Package.PackageWeight }
     * 
     */
    public ShipmentConfirmRequest.Shipment.Package.PackageWeight createShipmentConfirmRequestShipmentPackagePackageWeight() {
        return new ShipmentConfirmRequest.Shipment.Package.PackageWeight();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.PaymentInformation.Prepaid.BillShipper }
     * 
     */
    public ShipmentConfirmRequest.Shipment.PaymentInformation.Prepaid.BillShipper createShipmentConfirmRequestShipmentPaymentInformationPrepaidBillShipper() {
        return new ShipmentConfirmRequest.Shipment.PaymentInformation.Prepaid.BillShipper();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.ShipFrom.Address }
     * 
     */
    public ShipmentConfirmRequest.Shipment.ShipFrom.Address createShipmentConfirmRequestShipmentShipFromAddress() {
        return new ShipmentConfirmRequest.Shipment.ShipFrom.Address();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.ShipTo.Address }
     * 
     */
    public ShipmentConfirmRequest.Shipment.ShipTo.Address createShipmentConfirmRequestShipmentShipToAddress() {
        return new ShipmentConfirmRequest.Shipment.ShipTo.Address();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Shipment.Shipper.Address }
     * 
     */
    public ShipmentConfirmRequest.Shipment.Shipper.Address createShipmentConfirmRequestShipmentShipperAddress() {
        return new ShipmentConfirmRequest.Shipment.Shipper.Address();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.LabelSpecification.LabelPrintMethod }
     * 
     */
    public ShipmentConfirmRequest.LabelSpecification.LabelPrintMethod createShipmentConfirmRequestLabelSpecificationLabelPrintMethod() {
        return new ShipmentConfirmRequest.LabelSpecification.LabelPrintMethod();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.LabelSpecification.LabelImageFormat }
     * 
     */
    public ShipmentConfirmRequest.LabelSpecification.LabelImageFormat createShipmentConfirmRequestLabelSpecificationLabelImageFormat() {
        return new ShipmentConfirmRequest.LabelSpecification.LabelImageFormat();
    }

    /**
     * Create an instance of {@link ShipmentConfirmRequest.Request.TransactionReference }
     * 
     */
    public ShipmentConfirmRequest.Request.TransactionReference createShipmentConfirmRequestRequestTransactionReference() {
        return new ShipmentConfirmRequest.Request.TransactionReference();
    }

}
