//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 11:52:29 AM CST 
//


package main.java.com.cts.ptms.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.theopentutorials.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ShipmentAcceptResponseObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.theopentutorials.jaxb.beans
     * 
     */
    public ShipmentAcceptResponseObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse }
     * 
     */
    public ShipmentAcceptResponse createShipmentAcceptResponse() {
        return new ShipmentAcceptResponse();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults createShipmentAcceptResponseShipmentResults() {
        return new ShipmentAcceptResponse.ShipmentResults();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.PackageResults }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.PackageResults createShipmentAcceptResponseShipmentResultsPackageResults() {
        return new ShipmentAcceptResponse.ShipmentResults.PackageResults();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage createShipmentAcceptResponseShipmentResultsPackageResultsLabelImage() {
        return new ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.BillingWeight }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.BillingWeight createShipmentAcceptResponseShipmentResultsBillingWeight() {
        return new ShipmentAcceptResponse.ShipmentResults.BillingWeight();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.ShipmentCharges createShipmentAcceptResponseShipmentResultsShipmentCharges() {
        return new ShipmentAcceptResponse.ShipmentResults.ShipmentCharges();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.Response }
     * 
     */
    public ShipmentAcceptResponse.Response createShipmentAcceptResponseResponse() {
        return new ShipmentAcceptResponse.Response();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.ServiceOptionsCharges }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.PackageResults.ServiceOptionsCharges createShipmentAcceptResponseShipmentResultsPackageResultsServiceOptionsCharges() {
        return new ShipmentAcceptResponse.ShipmentResults.PackageResults.ServiceOptionsCharges();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage.LabelImageFormat }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage.LabelImageFormat createShipmentAcceptResponseShipmentResultsPackageResultsLabelImageLabelImageFormat() {
        return new ShipmentAcceptResponse.ShipmentResults.PackageResults.LabelImage.LabelImageFormat();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.BillingWeight.UnitOfMeasurement }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.BillingWeight.UnitOfMeasurement createShipmentAcceptResponseShipmentResultsBillingWeightUnitOfMeasurement() {
        return new ShipmentAcceptResponse.ShipmentResults.BillingWeight.UnitOfMeasurement();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TransportationCharges }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TransportationCharges createShipmentAcceptResponseShipmentResultsShipmentChargesTransportationCharges() {
        return new ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TransportationCharges();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.ServiceOptionsCharges }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.ServiceOptionsCharges createShipmentAcceptResponseShipmentResultsShipmentChargesServiceOptionsCharges() {
        return new ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.ServiceOptionsCharges();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TotalCharges }
     * 
     */
    public ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TotalCharges createShipmentAcceptResponseShipmentResultsShipmentChargesTotalCharges() {
        return new ShipmentAcceptResponse.ShipmentResults.ShipmentCharges.TotalCharges();
    }

    /**
     * Create an instance of {@link ShipmentAcceptResponse.Response.TransactionReference }
     * 
     */
    public ShipmentAcceptResponse.Response.TransactionReference createShipmentAcceptResponseResponseTransactionReference() {
        return new ShipmentAcceptResponse.Response.TransactionReference();
    }

}
