//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 10:06:02 AM CST 
//


package main.java.com.cts.ptms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Response">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TransactionReference">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ResponseStatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ResponseStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipmentCharges">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TransportationCharges">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ServiceOptionsCharges">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TotalCharges">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BillingWeight">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UnitOfMeasurement">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipmentIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipmentDigest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "shipmentCharges",
    "billingWeight",
    "shipmentIdentificationNumber",
    "shipmentDigest"
})
@XmlRootElement(name = "ShipmentConfirmResponse")
public class ShipmentConfirmResponse {

    @XmlElement(name = "Response", required = true)
    protected ShipmentConfirmResponse.Response response;
    @XmlElement(name = "ShipmentCharges", required = true)
    protected ShipmentConfirmResponse.ShipmentCharges shipmentCharges;
    @XmlElement(name = "BillingWeight", required = true)
    protected ShipmentConfirmResponse.BillingWeight billingWeight;
    @XmlElement(name = "ShipmentIdentificationNumber", required = true)
    protected String shipmentIdentificationNumber;
    @XmlElement(name = "ShipmentDigest", required = true)
    protected String shipmentDigest;
    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentConfirmResponse.Response }
     *     
     */
    public ShipmentConfirmResponse.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentConfirmResponse.Response }
     *     
     */
    public void setResponse(ShipmentConfirmResponse.Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the shipmentCharges property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentConfirmResponse.ShipmentCharges }
     *     
     */
    public ShipmentConfirmResponse.ShipmentCharges getShipmentCharges() {
        return shipmentCharges;
    }

    /**
     * Sets the value of the shipmentCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentConfirmResponse.ShipmentCharges }
     *     
     */
    public void setShipmentCharges(ShipmentConfirmResponse.ShipmentCharges value) {
        this.shipmentCharges = value;
    }

    /**
     * Gets the value of the billingWeight property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentConfirmResponse.BillingWeight }
     *     
     */
    public ShipmentConfirmResponse.BillingWeight getBillingWeight() {
        return billingWeight;
    }

    /**
     * Sets the value of the billingWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentConfirmResponse.BillingWeight }
     *     
     */
    public void setBillingWeight(ShipmentConfirmResponse.BillingWeight value) {
        this.billingWeight = value;
    }

    /**
     * Gets the value of the shipmentIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentIdentificationNumber() {
        return shipmentIdentificationNumber;
    }

    /**
     * Sets the value of the shipmentIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentIdentificationNumber(String value) {
        this.shipmentIdentificationNumber = value;
    }

    /**
     * Gets the value of the shipmentDigest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentDigest() {
        return shipmentDigest;
    }

    /**
     * Sets the value of the shipmentDigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentDigest(String value) {
        this.shipmentDigest = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UnitOfMeasurement">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unitOfMeasurement",
        "weight"
    })
    public static class BillingWeight {

        @XmlElement(name = "UnitOfMeasurement", required = true)
        protected ShipmentConfirmResponse.BillingWeight.UnitOfMeasurement unitOfMeasurement;
        @XmlElement(name = "Weight")
        protected float weight;

        /**
         * Gets the value of the unitOfMeasurement property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentConfirmResponse.BillingWeight.UnitOfMeasurement }
         *     
         */
        public ShipmentConfirmResponse.BillingWeight.UnitOfMeasurement getUnitOfMeasurement() {
            return unitOfMeasurement;
        }

        /**
         * Sets the value of the unitOfMeasurement property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentConfirmResponse.BillingWeight.UnitOfMeasurement }
         *     
         */
        public void setUnitOfMeasurement(ShipmentConfirmResponse.BillingWeight.UnitOfMeasurement value) {
            this.unitOfMeasurement = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         */
        public float getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         */
        public void setWeight(float value) {
            this.weight = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "code"
        })
        public static class UnitOfMeasurement {

            @XmlElement(name = "Code", required = true)
            protected String code;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TransactionReference">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ResponseStatusCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ResponseStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionReference",
        "responseStatusCode",
        "responseStatusDescription",
        "error"
    })
    public static class Response {

        @XmlElement(name = "TransactionReference", required = true)
        protected ShipmentConfirmResponse.Response.TransactionReference transactionReference;
        @XmlElement(name = "ResponseStatusCode")
        protected byte responseStatusCode;
        @XmlElement(name = "ResponseStatusDescription", required = true)
        protected String responseStatusDescription;
        @XmlElement(name = "Error", required = true)
        public Error error = new Error();
        /**
         * Gets the value of the transactionReference property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentConfirmResponse.Response.TransactionReference }
         *     
         */
        public ShipmentConfirmResponse.Response.TransactionReference getTransactionReference() {
            return transactionReference;
        }

        /**
         * Sets the value of the transactionReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentConfirmResponse.Response.TransactionReference }
         *     
         */
        public void setTransactionReference(ShipmentConfirmResponse.Response.TransactionReference value) {
            this.transactionReference = value;
        }

        /**
         * Gets the value of the responseStatusCode property.
         * 
         */
        public byte getResponseStatusCode() {
            return responseStatusCode;
        }

        /**
         * Sets the value of the responseStatusCode property.
         * 
         */
        public void setResponseStatusCode(byte value) {
            this.responseStatusCode = value;
        }

        /**
         * Gets the value of the responseStatusDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseStatusDescription() {
            return responseStatusDescription;
        }

        /**
         * Sets the value of the responseStatusDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseStatusDescription(String value) {
            this.responseStatusDescription = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CustomerContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customerContext"
        })
        public static class TransactionReference {

            @XmlElement(name = "CustomerContext", required = true)
            protected String customerContext;

            /**
             * Gets the value of the customerContext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerContext() {
                return customerContext;
            }

            /**
             * Sets the value of the customerContext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerContext(String value) {
                this.customerContext = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TransportationCharges">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ServiceOptionsCharges">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TotalCharges">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transportationCharges",
        "serviceOptionsCharges",
        "totalCharges"
    })
    public static class ShipmentCharges {

        @XmlElement(name = "TransportationCharges", required = true)
        protected ShipmentConfirmResponse.ShipmentCharges.TransportationCharges transportationCharges;
        @XmlElement(name = "ServiceOptionsCharges", required = true)
        protected ShipmentConfirmResponse.ShipmentCharges.ServiceOptionsCharges serviceOptionsCharges;
        @XmlElement(name = "TotalCharges", required = true)
        protected ShipmentConfirmResponse.ShipmentCharges.TotalCharges totalCharges;

        /**
         * Gets the value of the transportationCharges property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentConfirmResponse.ShipmentCharges.TransportationCharges }
         *     
         */
        public ShipmentConfirmResponse.ShipmentCharges.TransportationCharges getTransportationCharges() {
            return transportationCharges;
        }

        /**
         * Sets the value of the transportationCharges property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentConfirmResponse.ShipmentCharges.TransportationCharges }
         *     
         */
        public void setTransportationCharges(ShipmentConfirmResponse.ShipmentCharges.TransportationCharges value) {
            this.transportationCharges = value;
        }

        /**
         * Gets the value of the serviceOptionsCharges property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentConfirmResponse.ShipmentCharges.ServiceOptionsCharges }
         *     
         */
        public ShipmentConfirmResponse.ShipmentCharges.ServiceOptionsCharges getServiceOptionsCharges() {
            return serviceOptionsCharges;
        }

        /**
         * Sets the value of the serviceOptionsCharges property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentConfirmResponse.ShipmentCharges.ServiceOptionsCharges }
         *     
         */
        public void setServiceOptionsCharges(ShipmentConfirmResponse.ShipmentCharges.ServiceOptionsCharges value) {
            this.serviceOptionsCharges = value;
        }

        /**
         * Gets the value of the totalCharges property.
         * 
         * @return
         *     possible object is
         *     {@link ShipmentConfirmResponse.ShipmentCharges.TotalCharges }
         *     
         */
        public ShipmentConfirmResponse.ShipmentCharges.TotalCharges getTotalCharges() {
            return totalCharges;
        }

        /**
         * Sets the value of the totalCharges property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShipmentConfirmResponse.ShipmentCharges.TotalCharges }
         *     
         */
        public void setTotalCharges(ShipmentConfirmResponse.ShipmentCharges.TotalCharges value) {
            this.totalCharges = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "currencyCode",
            "monetaryValue"
        })
        public static class ServiceOptionsCharges {

            @XmlElement(name = "CurrencyCode", required = true)
            protected String currencyCode;
            @XmlElement(name = "MonetaryValue")
            protected float monetaryValue;

            /**
             * Gets the value of the currencyCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrencyCode() {
                return currencyCode;
            }

            /**
             * Sets the value of the currencyCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrencyCode(String value) {
                this.currencyCode = value;
            }

            /**
             * Gets the value of the monetaryValue property.
             * 
             */
            public float getMonetaryValue() {
                return monetaryValue;
            }

            /**
             * Sets the value of the monetaryValue property.
             * 
             */
            public void setMonetaryValue(float value) {
                this.monetaryValue = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "currencyCode",
            "monetaryValue"
        })
        public static class TotalCharges {

            @XmlElement(name = "CurrencyCode", required = true)
            protected String currencyCode;
            @XmlElement(name = "MonetaryValue")
            protected float monetaryValue;

            /**
             * Gets the value of the currencyCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrencyCode() {
                return currencyCode;
            }

            /**
             * Sets the value of the currencyCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrencyCode(String value) {
                this.currencyCode = value;
            }

            /**
             * Gets the value of the monetaryValue property.
             * 
             */
            public float getMonetaryValue() {
                return monetaryValue;
            }

            /**
             * Sets the value of the monetaryValue property.
             * 
             */
            public void setMonetaryValue(float value) {
                this.monetaryValue = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MonetaryValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "currencyCode",
            "monetaryValue"
        })
        public static class TransportationCharges {

            @XmlElement(name = "CurrencyCode", required = true)
            protected String currencyCode;
            @XmlElement(name = "MonetaryValue")
            protected float monetaryValue;

            /**
             * Gets the value of the currencyCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrencyCode() {
                return currencyCode;
            }

            /**
             * Sets the value of the currencyCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrencyCode(String value) {
                this.currencyCode = value;
            }

            /**
             * Gets the value of the monetaryValue property.
             * 
             */
            public float getMonetaryValue() {
                return monetaryValue;
            }

            /**
             * Sets the value of the monetaryValue property.
             * 
             */
            public void setMonetaryValue(float value) {
                this.monetaryValue = value;
            }

        }

    }

}
