//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 03:39:27 PM CST 
//


package main.java.com.cts.ptms.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}CartonNumber"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}DistributionCenter"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}OrderKey"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}OrderNumber"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}BillingAccountID"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}Status"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}CartonName"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}DatePlannedShipment"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}ShipVia"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}ShippingOptions"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}Weight"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}Length"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}Width"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}Height"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}CarrierReferenceNote"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}CarrierReferenceType"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}DataXML"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}ADDRESS" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}INTERNATIONAL_SHIP_UNIT"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}UPS_SHIP_UNIT"/>
 *         &lt;element ref="{http://ScanData.com/WTM/XMLSchemas/WTM_XMLSchema_11.00.0000.xsd}FEDEX_SHIP_UNIT"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cartonNumber",
    "distributionCenter",
    "orderKey",
    "orderNumber",
    "billingAccountID",
    "status",
    "cartonName",
    "datePlannedShipment",
    "shipVia",
    "shippingOptions",
    "weight",
    "length",
    "width",
    "height",
    "carrierReferenceNote",
    "carrierReferenceType",
    "dataXML",
    "address",
    "internationalshipunit",
    "upsshipunit",
    "fedexshipunit"
})
@XmlRootElement(name = "SHIP_UNIT")
public class SHIPUNIT {

    @XmlElement(name = "CartonNumber", required = true)
    protected BigInteger cartonNumber;
    @XmlElement(name = "DistributionCenter", required = true)
    protected BigInteger distributionCenter;
    @XmlElement(name = "OrderKey", required = true)
    protected BigInteger orderKey;
    @XmlElement(name = "OrderNumber", required = true)
    protected BigInteger orderNumber;
    @XmlElement(name = "BillingAccountID", required = true)
    protected BigInteger billingAccountID;
    @XmlElement(name = "Status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String status;
    @XmlElement(name = "CartonName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String cartonName;
    @XmlElement(name = "DatePlannedShipment", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String datePlannedShipment;
    @XmlElement(name = "ShipVia", required = true)
    protected BigInteger shipVia;
    @XmlElement(name = "ShippingOptions", required = true)
    protected ShippingOptions shippingOptions;
    @XmlElement(name = "Weight", required = true)
    protected BigInteger weight;
    @XmlElement(name = "Length", required = true)
    protected BigInteger length;
    @XmlElement(name = "Width", required = true)
    protected BigInteger width;
    @XmlElement(name = "Height", required = true)
    protected BigInteger height;
    @XmlElement(name = "CarrierReferenceNote", required = true)
    protected BigInteger carrierReferenceNote;
    @XmlElement(name = "CarrierReferenceType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String carrierReferenceType;
    @XmlElement(name = "DataXML", required = true)
    protected DataXML dataXML;
    @XmlElement(name = "ADDRESS", required = true)
    protected List<ADDRESS> address;
    @XmlElement(name = "INTERNATIONAL_SHIP_UNIT", required = true)
    protected INTERNATIONALSHIPUNIT internationalshipunit;
    @XmlElement(name = "UPS_SHIP_UNIT", required = true)
    protected UPSSHIPUNIT upsshipunit;
    @XmlElement(name = "FEDEX_SHIP_UNIT", required = true)
    protected FEDEXSHIPUNIT fedexshipunit;
    @XmlAttribute(name = "Version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String version;

    /**
     * Gets the value of the cartonNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCartonNumber() {
        return cartonNumber;
    }

    /**
     * Sets the value of the cartonNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCartonNumber(BigInteger value) {
        this.cartonNumber = value;
    }

    /**
     * Gets the value of the distributionCenter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDistributionCenter() {
        return distributionCenter;
    }

    /**
     * Sets the value of the distributionCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDistributionCenter(BigInteger value) {
        this.distributionCenter = value;
    }

    /**
     * Gets the value of the orderKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderKey() {
        return orderKey;
    }

    /**
     * Sets the value of the orderKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderKey(BigInteger value) {
        this.orderKey = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderNumber(BigInteger value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the billingAccountID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBillingAccountID() {
        return billingAccountID;
    }

    /**
     * Sets the value of the billingAccountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBillingAccountID(BigInteger value) {
        this.billingAccountID = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the cartonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCartonName() {
        return cartonName;
    }

    /**
     * Sets the value of the cartonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCartonName(String value) {
        this.cartonName = value;
    }

    /**
     * Gets the value of the datePlannedShipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatePlannedShipment() {
        return datePlannedShipment;
    }

    /**
     * Sets the value of the datePlannedShipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatePlannedShipment(String value) {
        this.datePlannedShipment = value;
    }

    /**
     * Gets the value of the shipVia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShipVia() {
        return shipVia;
    }

    /**
     * Sets the value of the shipVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShipVia(BigInteger value) {
        this.shipVia = value;
    }

    /**
     * Gets the value of the shippingOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingOptions }
     *     
     */
    public ShippingOptions getShippingOptions() {
        return shippingOptions;
    }

    /**
     * Sets the value of the shippingOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingOptions }
     *     
     */
    public void setShippingOptions(ShippingOptions value) {
        this.shippingOptions = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWeight(BigInteger value) {
        this.weight = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLength(BigInteger value) {
        this.length = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the carrierReferenceNote property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCarrierReferenceNote() {
        return carrierReferenceNote;
    }

    /**
     * Sets the value of the carrierReferenceNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCarrierReferenceNote(BigInteger value) {
        this.carrierReferenceNote = value;
    }

    /**
     * Gets the value of the carrierReferenceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierReferenceType() {
        return carrierReferenceType;
    }

    /**
     * Sets the value of the carrierReferenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierReferenceType(String value) {
        this.carrierReferenceType = value;
    }

    /**
     * Gets the value of the dataXML property.
     * 
     * @return
     *     possible object is
     *     {@link DataXML }
     *     
     */
    public DataXML getDataXML() {
        return dataXML;
    }

    /**
     * Sets the value of the dataXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataXML }
     *     
     */
    public void setDataXML(DataXML value) {
        this.dataXML = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADDRESS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ADDRESS }
     * 
     * 
     */
    public List<ADDRESS> getADDRESS() {
        if (address == null) {
            address = new ArrayList<ADDRESS>();
        }
        return this.address;
    }

    /**
     * Gets the value of the internationalshipunit property.
     * 
     * @return
     *     possible object is
     *     {@link INTERNATIONALSHIPUNIT }
     *     
     */
    public INTERNATIONALSHIPUNIT getINTERNATIONALSHIPUNIT() {
        return internationalshipunit;
    }

    /**
     * Sets the value of the internationalshipunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link INTERNATIONALSHIPUNIT }
     *     
     */
    public void setINTERNATIONALSHIPUNIT(INTERNATIONALSHIPUNIT value) {
        this.internationalshipunit = value;
    }

    /**
     * Gets the value of the upsshipunit property.
     * 
     * @return
     *     possible object is
     *     {@link UPSSHIPUNIT }
     *     
     */
    public UPSSHIPUNIT getUPSSHIPUNIT() {
        return upsshipunit;
    }

    /**
     * Sets the value of the upsshipunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UPSSHIPUNIT }
     *     
     */
    public void setUPSSHIPUNIT(UPSSHIPUNIT value) {
        this.upsshipunit = value;
    }

    /**
     * Gets the value of the fedexshipunit property.
     * 
     * @return
     *     possible object is
     *     {@link FEDEXSHIPUNIT }
     *     
     */
    public FEDEXSHIPUNIT getFEDEXSHIPUNIT() {
        return fedexshipunit;
    }

    /**
     * Sets the value of the fedexshipunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link FEDEXSHIPUNIT }
     *     
     */
    public void setFEDEXSHIPUNIT(FEDEXSHIPUNIT value) {
        this.fedexshipunit = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
