//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 04:45:15 PM CST 
//


package main.java.com.cts.ptms.model.confirm.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LabelPrintMethod" type="{}LabelPrintMethodCodeDescriptionType"/>
 *         &lt;element name="HTTPUserAgent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LabelStockSize" type="{}LabelStockSizeType" minOccurs="0"/>
 *         &lt;element name="LabelImageFormat" type="{}LabelImageFormatCodeDescriptionType"/>
 *         &lt;element name="Instruction" type="{}InstructionCodeDescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelSpecificationType", propOrder = {
    "labelPrintMethod",
    "httpUserAgent",
    "labelStockSize",
    "labelImageFormat",
    "instruction"
})
public class LabelSpecificationType {

    @XmlElement(name = "LabelPrintMethod", required = true)
    protected LabelPrintMethodCodeDescriptionType labelPrintMethod;
    @XmlElement(name = "HTTPUserAgent")
    protected String httpUserAgent;
    @XmlElement(name = "LabelStockSize")
    protected LabelStockSizeType labelStockSize;
    @XmlElement(name = "LabelImageFormat", required = true)
    protected LabelImageFormatCodeDescriptionType labelImageFormat;
    @XmlElement(name = "Instruction")
    protected List<InstructionCodeDescriptionType> instruction;

    /**
     * Gets the value of the labelPrintMethod property.
     * 
     * @return
     *     possible object is
     *     {@link LabelPrintMethodCodeDescriptionType }
     *     
     */
    public LabelPrintMethodCodeDescriptionType getLabelPrintMethod() {
        return labelPrintMethod;
    }

    /**
     * Sets the value of the labelPrintMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelPrintMethodCodeDescriptionType }
     *     
     */
    public void setLabelPrintMethod(LabelPrintMethodCodeDescriptionType value) {
        this.labelPrintMethod = value;
    }

    /**
     * Gets the value of the httpUserAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHTTPUserAgent() {
        return httpUserAgent;
    }

    /**
     * Sets the value of the httpUserAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHTTPUserAgent(String value) {
        this.httpUserAgent = value;
    }

    /**
     * Gets the value of the labelStockSize property.
     * 
     * @return
     *     possible object is
     *     {@link LabelStockSizeType }
     *     
     */
    public LabelStockSizeType getLabelStockSize() {
        return labelStockSize;
    }

    /**
     * Sets the value of the labelStockSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelStockSizeType }
     *     
     */
    public void setLabelStockSize(LabelStockSizeType value) {
        this.labelStockSize = value;
    }

    /**
     * Gets the value of the labelImageFormat property.
     * 
     * @return
     *     possible object is
     *     {@link LabelImageFormatCodeDescriptionType }
     *     
     */
    public LabelImageFormatCodeDescriptionType getLabelImageFormat() {
        return labelImageFormat;
    }

    /**
     * Sets the value of the labelImageFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelImageFormatCodeDescriptionType }
     *     
     */
    public void setLabelImageFormat(LabelImageFormatCodeDescriptionType value) {
        this.labelImageFormat = value;
    }

    /**
     * Gets the value of the instruction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instruction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstruction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstructionCodeDescriptionType }
     * 
     * 
     */
    public List<InstructionCodeDescriptionType> getInstruction() {
        if (instruction == null) {
            instruction = new ArrayList<InstructionCodeDescriptionType>();
        }
        return this.instruction;
    }

}
