//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 04:45:15 PM CST 
//


package main.java.com.cts.ptms.model.confirm.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageServiceOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageServiceOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryConfirmation" type="{}PackageServiceOptionsDeliveryConfirmationType" minOccurs="0"/>
 *         &lt;element name="InsuredValue" type="{}InsuredValueType" minOccurs="0"/>
 *         &lt;element name="COD" type="{}PackageServiceOptionsCODType" minOccurs="0"/>
 *         &lt;element name="AccessPointCOD" type="{}PackageServiceOptionsAccessPointCODType" minOccurs="0"/>
 *         &lt;element name="VerbalConfirmation" type="{}VerbalConfirmationType" minOccurs="0"/>
 *         &lt;element name="ShipperReleaseIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Notification" type="{}PackageServiceOptionsNotificationType" minOccurs="0"/>
 *         &lt;element name="DryIce" type="{}DryIceType" minOccurs="0"/>
 *         &lt;element name="UPSPremiumCareIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageServiceOptionsType", propOrder = {
    "deliveryConfirmation",
    "insuredValue",
    "cod",
    "accessPointCOD",
    "verbalConfirmation",
    "shipperReleaseIndicator",
    "notification",
    "dryIce",
    "upsPremiumCareIndicator"
})
public class PackageServiceOptionsType {

    @XmlElement(name = "DeliveryConfirmation")
    protected PackageServiceOptionsDeliveryConfirmationType deliveryConfirmation;
    @XmlElement(name = "InsuredValue")
    protected InsuredValueType insuredValue;
    @XmlElement(name = "COD")
    protected PackageServiceOptionsCODType cod;
    @XmlElement(name = "AccessPointCOD")
    protected PackageServiceOptionsAccessPointCODType accessPointCOD;
    @XmlElement(name = "VerbalConfirmation")
    protected VerbalConfirmationType verbalConfirmation;
    @XmlElement(name = "ShipperReleaseIndicator")
    protected String shipperReleaseIndicator;
    @XmlElement(name = "Notification")
    protected PackageServiceOptionsNotificationType notification;
    @XmlElement(name = "DryIce")
    protected DryIceType dryIce;
    @XmlElement(name = "UPSPremiumCareIndicator")
    protected String upsPremiumCareIndicator;

    /**
     * Gets the value of the deliveryConfirmation property.
     * 
     * @return
     *     possible object is
     *     {@link PackageServiceOptionsDeliveryConfirmationType }
     *     
     */
    public PackageServiceOptionsDeliveryConfirmationType getDeliveryConfirmation() {
        return deliveryConfirmation;
    }

    /**
     * Sets the value of the deliveryConfirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageServiceOptionsDeliveryConfirmationType }
     *     
     */
    public void setDeliveryConfirmation(PackageServiceOptionsDeliveryConfirmationType value) {
        this.deliveryConfirmation = value;
    }

    /**
     * Gets the value of the insuredValue property.
     * 
     * @return
     *     possible object is
     *     {@link InsuredValueType }
     *     
     */
    public InsuredValueType getInsuredValue() {
        return insuredValue;
    }

    /**
     * Sets the value of the insuredValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuredValueType }
     *     
     */
    public void setInsuredValue(InsuredValueType value) {
        this.insuredValue = value;
    }

    /**
     * Gets the value of the cod property.
     * 
     * @return
     *     possible object is
     *     {@link PackageServiceOptionsCODType }
     *     
     */
    public PackageServiceOptionsCODType getCOD() {
        return cod;
    }

    /**
     * Sets the value of the cod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageServiceOptionsCODType }
     *     
     */
    public void setCOD(PackageServiceOptionsCODType value) {
        this.cod = value;
    }

    /**
     * Gets the value of the accessPointCOD property.
     * 
     * @return
     *     possible object is
     *     {@link PackageServiceOptionsAccessPointCODType }
     *     
     */
    public PackageServiceOptionsAccessPointCODType getAccessPointCOD() {
        return accessPointCOD;
    }

    /**
     * Sets the value of the accessPointCOD property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageServiceOptionsAccessPointCODType }
     *     
     */
    public void setAccessPointCOD(PackageServiceOptionsAccessPointCODType value) {
        this.accessPointCOD = value;
    }

    /**
     * Gets the value of the verbalConfirmation property.
     * 
     * @return
     *     possible object is
     *     {@link VerbalConfirmationType }
     *     
     */
    public VerbalConfirmationType getVerbalConfirmation() {
        return verbalConfirmation;
    }

    /**
     * Sets the value of the verbalConfirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerbalConfirmationType }
     *     
     */
    public void setVerbalConfirmation(VerbalConfirmationType value) {
        this.verbalConfirmation = value;
    }

    /**
     * Gets the value of the shipperReleaseIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperReleaseIndicator() {
        return shipperReleaseIndicator;
    }

    /**
     * Sets the value of the shipperReleaseIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperReleaseIndicator(String value) {
        this.shipperReleaseIndicator = value;
    }

    /**
     * Gets the value of the notification property.
     * 
     * @return
     *     possible object is
     *     {@link PackageServiceOptionsNotificationType }
     *     
     */
    public PackageServiceOptionsNotificationType getNotification() {
        return notification;
    }

    /**
     * Sets the value of the notification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageServiceOptionsNotificationType }
     *     
     */
    public void setNotification(PackageServiceOptionsNotificationType value) {
        this.notification = value;
    }

    /**
     * Gets the value of the dryIce property.
     * 
     * @return
     *     possible object is
     *     {@link DryIceType }
     *     
     */
    public DryIceType getDryIce() {
        return dryIce;
    }

    /**
     * Sets the value of the dryIce property.
     * 
     * @param value
     *     allowed object is
     *     {@link DryIceType }
     *     
     */
    public void setDryIce(DryIceType value) {
        this.dryIce = value;
    }

    /**
     * Gets the value of the upsPremiumCareIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPSPremiumCareIndicator() {
        return upsPremiumCareIndicator;
    }

    /**
     * Sets the value of the upsPremiumCareIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPSPremiumCareIndicator(String value) {
        this.upsPremiumCareIndicator = value;
    }

}
