//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 04:45:15 PM CST 
//


package main.java.com.cts.ptms.model.confirm.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentChargeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentChargeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="BillShipper" type="{}BillShipperType" minOccurs="0"/>
 *           &lt;element name="BillReceiver" type="{}BillReceiverType" minOccurs="0"/>
 *           &lt;element name="BillThirdParty" type="{}ItemizedBillThirdPartyType" minOccurs="0"/>
 *           &lt;element name="ConsigneeBilled" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentChargeType", propOrder = {
    "type",
    "billShipper",
    "billReceiver",
    "billThirdParty",
    "consigneeBilled"
})
public class ShipmentChargeType {

    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "BillShipper")
    protected BillShipperType billShipper;
    @XmlElement(name = "BillReceiver")
    protected BillReceiverType billReceiver;
    @XmlElement(name = "BillThirdParty")
    protected ItemizedBillThirdPartyType billThirdParty;
    @XmlElement(name = "ConsigneeBilled")
    protected String consigneeBilled;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the billShipper property.
     * 
     * @return
     *     possible object is
     *     {@link BillShipperType }
     *     
     */
    public BillShipperType getBillShipper() {
        return billShipper;
    }

    /**
     * Sets the value of the billShipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillShipperType }
     *     
     */
    public void setBillShipper(BillShipperType value) {
        this.billShipper = value;
    }

    /**
     * Gets the value of the billReceiver property.
     * 
     * @return
     *     possible object is
     *     {@link BillReceiverType }
     *     
     */
    public BillReceiverType getBillReceiver() {
        return billReceiver;
    }

    /**
     * Sets the value of the billReceiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillReceiverType }
     *     
     */
    public void setBillReceiver(BillReceiverType value) {
        this.billReceiver = value;
    }

    /**
     * Gets the value of the billThirdParty property.
     * 
     * @return
     *     possible object is
     *     {@link ItemizedBillThirdPartyType }
     *     
     */
    public ItemizedBillThirdPartyType getBillThirdParty() {
        return billThirdParty;
    }

    /**
     * Sets the value of the billThirdParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemizedBillThirdPartyType }
     *     
     */
    public void setBillThirdParty(ItemizedBillThirdPartyType value) {
        this.billThirdParty = value;
    }

    /**
     * Gets the value of the consigneeBilled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsigneeBilled() {
        return consigneeBilled;
    }

    /**
     * Sets the value of the consigneeBilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsigneeBilled(String value) {
        this.consigneeBilled = value;
    }

}
