//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 04:44:35 PM CST 
//


package main.java.com.cts.ptms.model.accept.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TrackingNumber"/>
 *         &lt;element ref="{}ServiceOptionsCharges" minOccurs="0"/>
 *         &lt;element ref="{}LabelImage" minOccurs="0"/>
 *         &lt;element ref="{}Receipt" minOccurs="0"/>
 *         &lt;element name="USPSPICNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CN22Number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Form" type="{}IntlForms" minOccurs="0"/>
 *         &lt;element ref="{}Accessorial" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trackingNumber",
    "serviceOptionsCharges",
    "labelImage",
    "receipt",
    "uspspicNumber",
    "cn22Number",
    "form",
    "accessorial"
})
@XmlRootElement(name = "PackageResults")
public class PackageResults {

    @XmlElement(name = "TrackingNumber", required = true)
    protected String trackingNumber;
    @XmlElement(name = "ServiceOptionsCharges")
    protected MonetaryType serviceOptionsCharges;
    @XmlElement(name = "LabelImage")
    protected LabelImage labelImage;
    @XmlElement(name = "Receipt")
    protected Receipt receipt;
    @XmlElement(name = "USPSPICNumber")
    protected String uspspicNumber;
    @XmlElement(name = "CN22Number")
    protected String cn22Number;
    @XmlElement(name = "Form")
    protected IntlForms form;
    @XmlElement(name = "Accessorial")
    protected Accessorial accessorial;

    /**
     * Gets the value of the trackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the value of the trackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingNumber(String value) {
        this.trackingNumber = value;
    }

    /**
     * Gets the value of the serviceOptionsCharges property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryType }
     *     
     */
    public MonetaryType getServiceOptionsCharges() {
        return serviceOptionsCharges;
    }

    /**
     * Sets the value of the serviceOptionsCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryType }
     *     
     */
    public void setServiceOptionsCharges(MonetaryType value) {
        this.serviceOptionsCharges = value;
    }

    /**
     * Gets the value of the labelImage property.
     * 
     * @return
     *     possible object is
     *     {@link LabelImage }
     *     
     */
    public LabelImage getLabelImage() {
        return labelImage;
    }

    /**
     * Sets the value of the labelImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelImage }
     *     
     */
    public void setLabelImage(LabelImage value) {
        this.labelImage = value;
    }

    /**
     * Gets the value of the receipt property.
     * 
     * @return
     *     possible object is
     *     {@link Receipt }
     *     
     */
    public Receipt getReceipt() {
        return receipt;
    }

    /**
     * Sets the value of the receipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receipt }
     *     
     */
    public void setReceipt(Receipt value) {
        this.receipt = value;
    }

    /**
     * Gets the value of the uspspicNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSPSPICNumber() {
        return uspspicNumber;
    }

    /**
     * Sets the value of the uspspicNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSPSPICNumber(String value) {
        this.uspspicNumber = value;
    }

    /**
     * Gets the value of the cn22Number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCN22Number() {
        return cn22Number;
    }

    /**
     * Sets the value of the cn22Number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCN22Number(String value) {
        this.cn22Number = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link IntlForms }
     *     
     */
    public IntlForms getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntlForms }
     *     
     */
    public void setForm(IntlForms value) {
        this.form = value;
    }

    /**
     * Gets the value of the accessorial property.
     * 
     * @return
     *     possible object is
     *     {@link Accessorial }
     *     
     */
    public Accessorial getAccessorial() {
        return accessorial;
    }

    /**
     * Sets the value of the accessorial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accessorial }
     *     
     */
    public void setAccessorial(Accessorial value) {
        this.accessorial = value;
    }

}
