//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 12:13:44 PM CST 
//


package com.cts.ptms.model.tracking;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageServiceOptionsType", propOrder = {
    "cod",
    "signatureRequired",
    "importControl",
    "commercialInvoiceRemoval",
    "upScarbonneutral",
    "uspspicNumber",
    "exchangeBased",
    "packAndCollect"
})
public class PackageServiceOptions {

    @XmlElement(name = "SignatureRequired")
    protected CodeDescription signatureRequired;
    @XmlElement(name = "ImportControl")
    protected String importControl;
    @XmlElement(name = "CommercialInvoiceRemoval")
    protected String commercialInvoiceRemoval;
    @XmlElement(name = "UPScarbonneutral")
    protected String upScarbonneutral;
    @XmlElement(name = "USPSPICNumber")
    protected String uspspicNumber;
    @XmlElement(name = "ExchangeBased")
    protected String exchangeBased;
    @XmlElement(name = "PackAndCollect")
    protected String packAndCollect;
	/**
	 * @return the signatureRequired
	 */
	public CodeDescription getSignatureRequired() {
		return signatureRequired;
	}
	/**
	 * @param signatureRequired the signatureRequired to set
	 */
	public void setSignatureRequired(CodeDescription signatureRequired) {
		this.signatureRequired = signatureRequired;
	}
	/**
	 * @return the importControl
	 */
	public String getImportControl() {
		return importControl;
	}
	/**
	 * @param importControl the importControl to set
	 */
	public void setImportControl(String importControl) {
		this.importControl = importControl;
	}
	/**
	 * @return the commercialInvoiceRemoval
	 */
	public String getCommercialInvoiceRemoval() {
		return commercialInvoiceRemoval;
	}
	/**
	 * @param commercialInvoiceRemoval the commercialInvoiceRemoval to set
	 */
	public void setCommercialInvoiceRemoval(String commercialInvoiceRemoval) {
		this.commercialInvoiceRemoval = commercialInvoiceRemoval;
	}
	/**
	 * @return the upScarbonneutral
	 */
	public String getUpScarbonneutral() {
		return upScarbonneutral;
	}
	/**
	 * @param upScarbonneutral the upScarbonneutral to set
	 */
	public void setUpScarbonneutral(String upScarbonneutral) {
		this.upScarbonneutral = upScarbonneutral;
	}
	/**
	 * @return the uspspicNumber
	 */
	public String getUspspicNumber() {
		return uspspicNumber;
	}
	/**
	 * @param uspspicNumber the uspspicNumber to set
	 */
	public void setUspspicNumber(String uspspicNumber) {
		this.uspspicNumber = uspspicNumber;
	}
	/**
	 * @return the exchangeBased
	 */
	public String getExchangeBased() {
		return exchangeBased;
	}
	/**
	 * @param exchangeBased the exchangeBased to set
	 */
	public void setExchangeBased(String exchangeBased) {
		this.exchangeBased = exchangeBased;
	}
	/**
	 * @return the packAndCollect
	 */
	public String getPackAndCollect() {
		return packAndCollect;
	}
	/**
	 * @param packAndCollect the packAndCollect to set
	 */
	public void setPackAndCollect(String packAndCollect) {
		this.packAndCollect = packAndCollect;
	}

    

}
