//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 12:13:44 PM CST 
//


package com.cts.ptms.model.tracking;

import java.util.List;


public class Shipment {

    private String shipmentIdentificationNumber;
    private Shipper shipper;
    private ShipTo shipTo;
    private Weight shipmentWeight;
    private CodeType service;
    private List<ShipmentReferenceNumber> referenceNumber;
    private CurrentStatus currentStatus;
    private String pickupDate;
    private List<ShipmentActivity> activity;
    private String scheduledDeliveryDate;
    private String scheduledDeliveryTime;
    private DeliveryDateUnavailable deliveryDateUnavailable;
    private List<Package> _package;
	/**
	 * @return the shipmentIdentificationNumber
	 */
	public String getShipmentIdentificationNumber() {
		return shipmentIdentificationNumber;
	}
	/**
	 * @param shipmentIdentificationNumber the shipmentIdentificationNumber to set
	 */
	public void setShipmentIdentificationNumber(String shipmentIdentificationNumber) {
		this.shipmentIdentificationNumber = shipmentIdentificationNumber;
	}
	/**
	 * @return the shipper
	 */
	public Shipper getShipper() {
		return shipper;
	}
	/**
	 * @param shipper the shipper to set
	 */
	public void setShipper(Shipper shipper) {
		this.shipper = shipper;
	}
	/**
	 * @return the shipTo
	 */
	public ShipTo getShipTo() {
		return shipTo;
	}
	/**
	 * @param shipTo the shipTo to set
	 */
	public void setShipTo(ShipTo shipTo) {
		this.shipTo = shipTo;
	}
	/**
	 * @return the shipmentWeight
	 */
	public Weight getShipmentWeight() {
		return shipmentWeight;
	}
	/**
	 * @param shipmentWeight the shipmentWeight to set
	 */
	public void setShipmentWeight(Weight shipmentWeight) {
		this.shipmentWeight = shipmentWeight;
	}
	/**
	 * @return the service
	 */
	public CodeType getService() {
		return service;
	}
	/**
	 * @param service the service to set
	 */
	public void setService(CodeType service) {
		this.service = service;
	}
	/**
	 * @return the referenceNumber
	 */
	public List<ShipmentReferenceNumber> getReferenceNumber() {
		return referenceNumber;
	}
	/**
	 * @param referenceNumber the referenceNumber to set
	 */
	public void setReferenceNumber(List<ShipmentReferenceNumber> referenceNumber) {
		this.referenceNumber = referenceNumber;
	}
	/**
	 * @return the currentStatus
	 */
	public CurrentStatus getCurrentStatus() {
		return currentStatus;
	}
	/**
	 * @param currentStatus the currentStatus to set
	 */
	public void setCurrentStatus(CurrentStatus currentStatus) {
		this.currentStatus = currentStatus;
	}
	/**
	 * @return the pickupDate
	 */
	public String getPickupDate() {
		return pickupDate;
	}
	/**
	 * @param pickupDate the pickupDate to set
	 */
	public void setPickupDate(String pickupDate) {
		this.pickupDate = pickupDate;
	}
	/**
	 * @return the activity
	 */
	public List<ShipmentActivity> getActivity() {
		return activity;
	}
	/**
	 * @param activity the activity to set
	 */
	public void setActivity(List<ShipmentActivity> activity) {
		this.activity = activity;
	}
	/**
	 * @return the scheduledDeliveryDate
	 */
	public String getScheduledDeliveryDate() {
		return scheduledDeliveryDate;
	}
	/**
	 * @param scheduledDeliveryDate the scheduledDeliveryDate to set
	 */
	public void setScheduledDeliveryDate(String scheduledDeliveryDate) {
		this.scheduledDeliveryDate = scheduledDeliveryDate;
	}
	/**
	 * @return the scheduledDeliveryTime
	 */
	public String getScheduledDeliveryTime() {
		return scheduledDeliveryTime;
	}
	/**
	 * @param scheduledDeliveryTime the scheduledDeliveryTime to set
	 */
	public void setScheduledDeliveryTime(String scheduledDeliveryTime) {
		this.scheduledDeliveryTime = scheduledDeliveryTime;
	}
	/**
	 * @return the deliveryDateUnavailable
	 */
	public DeliveryDateUnavailable getDeliveryDateUnavailable() {
		return deliveryDateUnavailable;
	}
	/**
	 * @param deliveryDateUnavailable the deliveryDateUnavailable to set
	 */
	public void setDeliveryDateUnavailable(DeliveryDateUnavailable deliveryDateUnavailable) {
		this.deliveryDateUnavailable = deliveryDateUnavailable;
	}
	/**
	 * @return the _package
	 */
	public List<Package> get_package() {
		return _package;
	}
	/**
	 * @param _package the _package to set
	 */
	public void set_package(List<Package> _package) {
		this._package = _package;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Shipment [shipmentIdentificationNumber=" + shipmentIdentificationNumber + ", shipper=" + shipper
				+ ", shipTo=" + shipTo + ", shipmentWeight=" + shipmentWeight + ", service=" + service
				+ ", referenceNumber=" + referenceNumber + ", currentStatus=" + currentStatus + ", pickupDate="
				+ pickupDate + ", activity=" + activity + ", scheduledDeliveryDate=" + scheduledDeliveryDate
				+ ", scheduledDeliveryTime=" + scheduledDeliveryTime + ", deliveryDateUnavailable="
				+ deliveryDateUnavailable + ", _package=" + _package + "]";
	}
    
    


}
