//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 12:13:16 PM CST 
//


package com.cts.ptms.model.tracking;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestAction",
    "requestOption",
    "trackingNumber"
})
@XmlRootElement(name = "TrackRequestDetails")
public class TrackRequestDetails implements Serializable{

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -650156458847982808L;

	@XmlElement(name = "RequestAction", required = true)
    protected String requestAction;
	
    @XmlElement(name = "RequestOption")
    protected List<String> requestOptions;
    
    @XmlElement(name = "TrackingNumber")
    protected String trackingNumber;

	/**
	 * @return the requestAction
	 */
	public String getRequestAction() {
		return requestAction;
	}

	/**
	 * @param requestAction the requestAction to set
	 */
	public void setRequestAction(String requestAction) {
		this.requestAction = requestAction;
	}

	/**
	 * @return the requestOptions
	 */
	public List<String> getRequestOptions() {
		if (requestOptions == null) {
			requestOptions = new ArrayList<String>(0);
		}
		return requestOptions;
	}

	/**
	 * @return the trackingNumber
	 */
	public String getTrackingNumber() {
		return trackingNumber;
	}

	/**
	 * @param trackingNumber the trackingNumber to set
	 */
	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}
    
}
